### ISSUE TITLE
NNBD makes more sense with Union Types

### ISSUE THREAD

**Issue by cgarciae** [chalin/DEP-non-null#11]
The proposal states

> That is, generally speaking, an unadorned class type T will represent the non-null type consisting (strictly) of instances of T. When needed, the meta type annotation ? can be used; ?T denotes the nullable type derived from T, consisting of values from T or null.

Doesn't the statement 

> T or null

practically imply/begs for _union types_? Ceylon does this beautifully where `String?` is short hand for `String | Null`. Dart could integrate the same approach now that its making breaking changes.

**Comment by chalin** [comment]
Yes, that is what is suggested in [B.3.1. Union type interoperability](https://github.com/chalin/DEP-non-null/blob/master/doc/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md#uti).
