### ISSUE TITLE
More specific than rules make `S << T` for all S and T

### ISSUE THREAD

**Issue by leafpetersen** [chalin/DEP-non-null#14]
Per section B.3.1.b, consider the question of whether `?S <: ?T` for arbitrary S and T.

Per the definition, it suffices to show that `?S << ?T` (with bottom substituted on the left, but that's irrelevant here).

Per B.3.1.b, it suffices to show that `Null << ?T`, which follows directly from the first part of B.3.1.b.

I think perhaps you intend to have a restriction here:
 `• ?V << S iff Null << S or V << S.`
that S is not nullable?  This doesn't solve the issue though, because you can get around this with transitivity:

To show that `?S << ?T`, it suffices to show (by the transitivity rule) that `?S << T` and `T << ?T`.

`T << ?T` holds by definition (section B.3.1.b)

To show `?S << T`, it suffices to show (by the rule quoted above) that `Null << T`. 

By transitivity, it suffices to show that `Null <: ?T` and `?T << T`.  

`Null < ?T` holds by definition (section B.3.1.b)

`?T << T` holds because of the rule quote above: note that T is non-nullable and hence satisfies the restriction, and `T << T` by definition.

Given this, you can also now leverage this up to show that `S << T` for non-nullable S and T as well.  By the previous derivation, we have that `?S << ?T`, and we also have that `S << ?S` and `T << ?T`, so by transitivity (twice) we have `S << T`.

**Comment by chalin** [comment]
Silly transcription errors on my part (the and/or operators traded definitions :). Sorry about that (I'm trying to juggle too many projects at the same time). I'm glad you are catching these.

So the two rules
-   ?_V_ << _S_ **iff** `Null` << _S_ ~~**or**~~ _V_ << _S_.
-   _T_ << ?_U_ only if _T_ << `Null` ~~**and**~~ _T_ << _U_.

should read:
- ?_V_ << _S_ **iff** `Null` << _S_ **and** _V_ << _S_.
- _T_ << ?_U_ if _T_ << `Null` **or** _T_ << _U_.

But I see now that the second rule follows from the other properties so I'll drop it.

I think that this should address your concerns so I'll close this issue for now. If not, feel free to reopen it.
