### ISSUE TITLE
Null is de-facto equivalent to bottom

### ISSUE THREAD

**Issue by leafpetersen** [chalin/DEP-non-null#15]
Per section B.3.b.1, we have that:

Null << ?T

Per this rule:
`• ?V << S iff Null << S or V << S.`
we have that `?T << T`.

So by transitivity, we have that `Null << T` for arbitrary T.  Therefore, by the definition of subtyping, we have that `Null <: T`.

My understanding was that the intention was that Null would not be a bottom type, so that assigning null to a non-nullable type would generate a warning.

**Comment by chalin** [comment]
Right. Same incorrect rule causing havoc :). This should be addressed by the updates of 6ad3fbcfd3c4bf55774b5db8d3f3515b23582b1b.
