### ISSUE TITLE
More specific than is not a partial order

### ISSUE THREAD

**Issue by leafpetersen** [chalin/DEP-non-null#16]
I think this is related to #14 and #15, but just to call it out specifically:

The spec currently defines the `<<` relation as a partial order.  This no longer holds in this proposal.  To see this, note that:

`int << ?int << int`

`int << ?int` by definition

`int? << int` by rule: `• ?V << S iff Null << S or V << S`

**Comment by chalin** [comment]
This should be addressed by the updates of 6ad3fbcfd3c4bf55774b5db8d3f3515b23582b1b.

Btw, looking at the [plain text](https://github.com/chalin/DEP-non-null/commit/6ad3fbcfd3c4bf55774b5db8d3f3515b23582b1b#diff-5bc8c863bdf1e1de5321fd967d455164) or [rich text](https://github.com/chalin/DEP-non-null/commit/6ad3fbcfd3c4bf55774b5db8d3f3515b23582b1b?short_path=5bc8c86#diff-5bc8c863bdf1e1de5321fd967d455164) diff of the generated .md file you can quickly see what has changed.
