### ISSUE TITLE
Better name of _ObjectOrNull?

### ISSUE THREAD

**Issue by munificent** [chalin/DEP-non-null#4]
This is bikeshedding, of course, but what do you think about something that's a little less of a mouthful? Maybe `_Any` (which is what Scala uses for this) or `_Anything`?

**Comment by chalin** [comment]
IMHO, `_Any` (and variants) should be avoided since [`any` is TypeScript's equivalent](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#31-the-any-type) of Dart's `dynamic`. Ok, sold on `_Anything`.
