### ISSUE TITLE
Default values for non-local variables.

### ISSUE THREAD

**Issue by zoechi** [chalin/DEP-non-null#8]
At first, thanks a lot for this work! 
I would love to have this realized. 

It would be nice if 
`int x; String s;` (NNBD) would be initialized to `0`, `''` automatically.
This could work for all types which have a default constructor. 
At least some syntactic shugar should allow easy default initialization. 
This might be out of scope but I think it's related closely enough to be mentioned at least.

**Comment by chalin** [comment]
@zoechi, thanks for your support of this proposal.

I agree that type-specific initialization defaults are related, and I have added [B.4.2(b)](https://github.com/chalin/DEP-non-null/blob/master/doc/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md#type-specific-init) as a suggested means of providing this. Let me know what you think --- yes, I know that it isn't quite fully "automatic", or more specifically, it isn't described as _the_ implicit default mechanism for initialization, but the given proposal only requires one extra character to be typed on the part of the developer :). In any case, making it _the_ implicit default mechanism for initialization would likely be a hard sell.

**Comment by zoechi** [comment]
Sure, NN+NNBD would be awesome to have. 
I again forgot the limitations optional types impose here but your proposed solution look fine. 
What are the reasons introducing a factory constructor instead of using the default constructor? It allows more control but it's also more verbose.

**Comment by chalin** [comment]
For one thing `int` doesn't have a default constructor :). But more generally, a generative constructor necessarily creates a new instance every time. Using a factory constructor allows a (presumably immutable) instance to be reused. Verbosity should not be an issue since the desugaring would be automatic.

**Comment by zoechi** [comment]
Good point :+1:

**Comment by munificent** [comment]
> It would be nice if `int x; String s;` (NNBD) would be initialized to 0, '' automatically.

I'd actually prefer the opposite:

``` dart
var x = 0;
var s = "";
```

This should infer that `x` has type `int` and `s` has type `String`. I would _much_ rather infer types from values than values from types. I think the former is a lot more in line with Dart's philosophy.

**Comment by chalin** [comment]
Type inference is nice indeed for local variables, but it is generally not tractable for other kinds of variables, such as instance variables (which, I believe, is the main use case @zoechi was making reference to --- if this is the case @zoechi, maybe consider updating the issue title to something like "Default values for non-local variables").

**Comment by zoechi** [comment]
For local variables inferring is preferred, but for instance variables and default values for optional positional and named arguments it would be very convenient.

**Comment by jmesserly** [comment]
> I would much rather infer types from values than values from types.

Consider a generic type:

``` dart
class Point<T> {
  !T x;
  !T y;
}
```

Or generic methods:

``` dart
/// Returns the first value of [source], otherwise returns the default value of T.
T firstOrDefault<T>(Iterable<T> source) ...
```

(taking a random example from C# [Enumerable](https://msdn.microsoft.com/en-us/library/vstudio/bb340482%28v=vs.100%29.aspx) extension methods)

The [DEFAULT_INIT](https://github.com/chalin/DEP-non-null/blob/master/doc/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md#b-implicit-type-specific-initialization-of-non-null-variables) mechanism potentially provides a way to address this, if you have a way of requiring the type T implements it.

That said, you could alternatively design these types so the default value is passed in.

**Comment by lrhn** [comment]
I think it's problematic if type assertions influence behavior, which is needed for this to work.
Dart has so far been very strict in enforcing that type assertions have no effect in production mode. If they change the default initialization value, then that's no longer the case.
It might be worth it anyway, but that'll require very good arguments.
